# Use the official Node.js image as a base image
FROM node:18

# Create and set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

RUN npm rebuild bcrypt --build-from-source

# Expose the port the app runs on
EXPOSE 3002

# Command to run the app
CMD ["sh", "-c", "npm", "start"]
